
name: Create Release

on:
  push: {branches: master}
  pull_request: {branches: master}
  repository_dispatch:

jobs:
  job_1:
    name: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - run: npm ci
    - run: npm run build
    - name: Use coturiv/setup-ionic
      uses: coturiv/setup-ionic@v1
    - name: Run cordova project tests
      run: |
        npm install -g @ionic/cli cordova-res
        ionic info
        ionic cordova platform add android@latest
        ionic cordova build android
