
name: Create Release

on:
  push: {branches: master}
  pull_request: {branches: master}
  repository_dispatch:

jobs:
  job_1:
    name: test
    runs-on: ubuntu-latest
    steps:
    - name: Use coturiv/setup-ionic
      uses: coturiv/setup-ionic@v1
    - name: Build
      run: |
        ionic cordova build android --prod
